# Generated by Django 2.1.2 on 2018-10-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upTime', models.DateTimeField(auto_now=True)),
                ('crateTime', models.DateTimeField(auto_now_add=True)),
                ('apk_name', models.TextField()),
                ('apk_url', models.TextField()),
                ('app_version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JokeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashId', models.CharField(max_length=35, unique=True)),
                ('content', models.TextField()),
                ('unixtime', models.IntegerField()),
                ('updatetime', models.DateTimeField()),
                ('url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userId', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('accountNumber', models.TextField(unique=True)),
                ('upTime', models.DateTimeField(auto_now=True)),
                ('crateTime', models.DateTimeField(auto_now_add=True)),
                ('userName', models.TextField()),
                ('passWord', models.TextField()),
                ('userLogo', models.TextField()),
                ('userPhone', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='apkfilemodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserModel'),
        ),
    ]
